name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Format code with autopep8
      run: |
        autopep8 --in-place --recursive .
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Auto format code with autopep8" || echo "No changes to commit"
        git push || echo "No changes to push"

  badges:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Setup
      run: |
        mkdir tmp
        sudo apt-get install -y libxml2-utils
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pylint
      run: |
        pylint src tests > tmp/pylint_output.txt
        echo "PYLINT_EXIT_CODE=$?" >> $GITHUB_ENV
      continue-on-error: true 

    - name: Run pyright
      run: |
        pyright src/* tests/*
        echo "PYRIGHT_EXIT_CODE=$?" >> $GITHUB_ENV
      continue-on-error: true 

    - name: Run pytest
      run: |
        pytest --cov=src --cov-report=json:tmp/coverage.json --junitxml=tmp/pytest_output.xml
        echo "PYTEST_EXIT_CODE=$?" >> $GITHUB_ENV
      continue-on-error: true

    - name: Extract number of tests, coverage, and determine result
      run: |
        NUM_TESTS=$(xmllint --xpath 'string(//testsuite/@tests)' tmp/pytest_output.xml)
        COVERAGE=$(jq '.totals.percent_covered' tmp/coverage.json | awk '{printf "%.0f", $1}')

        # Determine the result of the tests
        if [ ${{ env.PYTEST_EXIT_CODE }} -eq 0 ]; then
          TESTS_STATUS="passing"
          TESTS_COLOR="brightgreen"
        else
          TESTS_STATUS="failing"
          TESTS_COLOR="red"
        fi

        # Determine coverage badge color
        if [ "$COVERAGE" -ge 90 ]; then
          COVERAGE_COLOR="brightgreen"
        elif [ "$COVERAGE" -ge 80 ]; then
          COVERAGE_COLOR="green"
        elif [ "$COVERAGE" -ge 70 ]; then
          COVERAGE_COLOR="yellowgreen"
        elif [ "$COVERAGE" -ge 60 ]; then
          COVERAGE_COLOR="yellow"
        elif [ "$COVERAGE" -ge 50 ]; then
          COVERAGE_COLOR="orange"
        else
          COVERAGE_COLOR="red"
        fi

        # Generate badge URLs
        TOTAL_TESTS_BADGE_URL="https://img.shields.io/badge/tests-${NUM_TESTS}-blue?logo=pytest&logoColor=white"
        CODE_COVERAGE_BADGE_URL="https://img.shields.io/badge/coverage-${COVERAGE}%25-${COVERAGE_COLOR}"
        PYTEST_STATUS_BADGE_URL="https://img.shields.io/badge/PyTest-${TESTS_STATUS}-${TESTS_COLOR}?logo=pytest&logoColor=white"

        # Export the badge URLs to the GitHub environment for use in later steps
        echo "TOTAL_TESTS_BADGE_URL=$TOTAL_TESTS_BADGE_URL" >> $GITHUB_ENV
        echo "CODE_COVERAGE_BADGE_URL=$CODE_COVERAGE_BADGE_URL" >> $GITHUB_ENV
        echo "PYTEST_STATUS_BADGE_URL=$PYTEST_STATUS_BADGE_URL" >> $GITHUB_ENV

        # Echo the badge URLs
        echo "Total test badge URL: $TOTAL_TESTS_BADGE_URL"
        echo "Code coverage badge URL: $CODE_COVERAGE_BADGE_URL"
        echo "PyTest status badge URL: $PYTEST_STATUS_BADGE_URL"


    - name: Update README with pylint badge
      run: |
        SCORE=$(grep -oP '(?<=rated at )[0-9]+\.[0-9]+' tmp/pylint_output.txt)
        if [ "$(echo "$SCORE < 5" | bc)" -eq 1 ]; then
          COLOR="red"
        elif [ "$(echo "$SCORE < 8" | bc)" -eq 1 ]; then
          COLOR="orange"
        elif [ "$(echo "$SCORE < 10" | bc)" -eq 1 ]; then
          COLOR="yellow"
        else
          COLOR="brightgreen"
        fi

        # Generate badge URL
        PYLINT_BADGE_URL="https://img.shields.io/badge/pylint-${SCORE}-${COLOR}"
        echo "PYLINT_BADGE_URL=$PYLINT_BADGE_URL" >> $GITHUB_ENV
        echo "PyTest status badge URL: $PYLINT_BADGE_URL"


    - name: Update README with pyright badge
      run: |
        # Generate badge URL
        BADGE_COLOR=$( [ $PYRIGHT_EXIT_CODE -eq 0 ] && echo "passing-brightgreen" || echo "failing-red" )
        PYRIGHT_BADGE_URL="https://img.shields.io/badge/pyright-${BADGE_COLOR}"
        echo "PYRIGHT_BADGE_URL=$PYRIGHT_BADGE_URL" >> $GITHUB_ENV
        echo "PyTest status badge URL: $PYRIGHT_BADGE_URL"
        
    - name: Update README with all the badges
      run: |
        sed -i '/!\[badge_pylint\]/c\![badge_pylint]('"$PYLINT_BADGE_URL"')' README.md
        sed -i '/!\[badge_pyright\]/c\![badge_pyright]('"$PYRIGHT_BADGE_URL"')' README.md
        sed -i '/!\[badge_total_tests\]/c\![badge_total_tests]('"$TOTAL_TESTS_BADGE_URL"')' README.md
        sed -i '/!\[badge_code_coverage\]/c\![badge_code_coverage]('"$CODE_COVERAGE_BADGE_URL"')' README.md
        sed -i '/!\[badge_pytest_status\]/c\![badge_pytest_status]('"$PYTEST_STATUS_BADGE_URL"')' README.md

        rm -rf tmp
        
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git checkout main
        git pull
        
        if git diff --quiet; then
            echo "No changes to commit"
        else
            git add README.md
            git commit -m "Update Pyright badge in README"
            git push
        fi
        
    - name: Fail if any tool failed
      run: |
        for TOOL in PYRIGHT PYLINT PYTEST; do
          EXIT_CODE_VAR="${TOOL}_EXIT_CODE"
          EXIT_CODE="${!EXIT_CODE_VAR}"
          if [ "$EXIT_CODE" -ne 0 ]; then
            echo "$TOOL failed, marking job as failed."
            exit 1
          fi
        done
